// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmCmGywtriZBnMdHY9I3o6VC9gHo2x58A',
    appId: '1:458501872917:web:7d121bc3da2597fa1edd1c',
    messagingSenderId: '458501872917',
    projectId: 'hyphen-roundrobin',
    authDomain: 'hyphen-roundrobin.firebaseapp.com',
    storageBucket: 'hyphen-roundrobin.appspot.com',
    measurementId: 'G-NREJSP0J27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmZzKPhVK0ljZNgAMFBw95nt2UkKGptbg',
    appId: '1:458501872917:android:811bbc9ae969c9db1edd1c',
    messagingSenderId: '458501872917',
    projectId: 'hyphen-roundrobin',
    storageBucket: 'hyphen-roundrobin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPiCkDWi3-oLCtd9AF30e2jlgrLsdlCI0',
    appId: '1:458501872917:ios:c5aa0937318f9d4e1edd1c',
    messagingSenderId: '458501872917',
    projectId: 'hyphen-roundrobin',
    storageBucket: 'hyphen-roundrobin.appspot.com',
    iosClientId: '458501872917-qp3pnb185uosjc2mf520r05ig2gs14em.apps.googleusercontent.com',
    iosBundleId: 'com.example.hyphen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPiCkDWi3-oLCtd9AF30e2jlgrLsdlCI0',
    appId: '1:458501872917:ios:c5aa0937318f9d4e1edd1c',
    messagingSenderId: '458501872917',
    projectId: 'hyphen-roundrobin',
    storageBucket: 'hyphen-roundrobin.appspot.com',
    iosClientId: '458501872917-qp3pnb185uosjc2mf520r05ig2gs14em.apps.googleusercontent.com',
    iosBundleId: 'com.example.hyphen',
  );
}
